### PR TITLE
feat: Add volume-control on lyrics page | 在全屏界面添加了音量控制

### PR DESCRIPTION
**Pull request by logres**
I try to add volume control on the lyrics page to satisfy issue #273.

Before:
image

After:
image

Wish I can get a review from you.

### CODE REVIEW

**Comment by Shaw-young** [comment]
It is a good try to add a volume control and makes the page more user-friendly than before. NICE!

**Comment by Maylve** [comment]
变得更方便了啊，真不错

**Comment by youyan0122** [comment]
一直显示登录成功，请稍等

**Comment by qier222** [comment]
这块的UI还没想好，暂时不加这个功能

**Pull request closed without merging**
